<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="V_Tour.aspx.cs" Inherits="WebApplication1.V_Tour" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <Table style="width:100%;">
        <tr><td> <img src="V_Tour/bhita.jpg" style="height: 447px; width: 93%" /> </td><td style="color: #FFFFFF; font-size: medium; font-family: 'Bookman Old Style'; text-align:justify;">Bhita is an ancient city on the bank of the Yamuna about 22 KM away from Allahabad unravels the story of a culture more than 2800 years old. Alexander Cunningham visited the site in the year 1872. He had come across a cut section through the rampart on the south-eastern side of central mound having the defences of the old town Bhita. John Marshall excavated the site in 1909-10. Out of five layers unearthed, the earliest period of this mound, represented by a deposit of black slipped ware, is datable to 8th to 7th BCE, followed by Northern Black Polished Ware dated to the beginning of 7th century BCE continued up to 2nd Century BCE. Likewise, the latest occupation is identified as contemporary to the Gupta period. A good number of antiquities have been recovered from Bhita. Among these antiquities a wide variety of Terracotta occupies a prime position. They include human and animal figurines, beads, rattle, wheel, toy cart, hopscotch stopper, weight etc.

Indian Museum, Kolkata has a sizeable collection of Bhita terracotta in their possession. The collection ranges from human figurines, faces to household objects, toys etc. It is an endeavour to project some of these specimens</td></tr>
        <tr><td><img src="V_Tour/naga.jpg" /></td><td style="color: #FFFFFF; font-family: 'Bookman Old Style'; font-size: medium; text-align:justify;">The Nagas, inhabit a narrow strip of the mountainous region between the Brahmaputra valley of Assam and the neighbouring Burma, the hilly areas of northern and eastern Manipur and a part of the Kachar Hills of Assam. Linguistically the Nagas belong to the Tibeto-Burman language group. The Nagas are the most numerous tribal group of north eastern India. It is composed of fourteen major tribes: Angami, Ao, Chakhesang, Chang, Khiemnungan, Konyak, Lotha, Phom, Rengama, Sangtam, Sema, Yimchunger, Zeliangrong, Kuki and several subtribes. Negaland is basically governed by an agricultural economy; about 90 per cent of the population depend on the produce of their fields for their livelihood. Heavy rainfall facilitates intensive agricultural activities. Rice, maize, millet, Job’s tears (Coix lacrima-jobi) and potatoes are the main crops.</td></tr>
        <tr><td><img src="V_Tour/mathura.jpg"</td><td style="color:#FFFFFF; font-family:'Bookman Old Style';font-size:medium;text-align:justify;">Mathura was the eastern headquater of the vast Kushana Empire and it had close administrative and culture links with the region of Gandhara in west. Both witnessed a golden time under the Kushanas. The Mathura and Gandhara schools of art which emerged and flourished almost simultaneously, freely intermixed and exchanged their artistic trends.The Mathura style reached its Zenith in the Gupta period, 4th-6th century A.D. when the figure became slim and slender and the expression on the face was marked with a super natural bliss and serenity. The Gupta sculptures are known for a unique combination of beauty and spirit. Inscriptions recorded on several sculptures have considerably enhanced their cultural significance.</td></tr>
        <tr><td><img src="V_Tour/masks.jpg" /></td><td style="color:#FFFFFF; font-family:'Bookman Old Style';font-size:medium;text-align:justify;">Mask is an art of transformation, concealing the identity of the performer and invests the actor with an alternative identity. It is used to take on the persona of the other – a person, a deity, an animal or a cosmic character. The performer in the mask dance is looked upon as an empowered person, whose socially ascribed identity is subsumed to the identity of the character that he depicts with the help of the mask.

Masks and their use in performances and religious ritual are an ancient tradition of a wide variety of communities in different parts of the world.</td></tr>
        <tr><td><img src="V_Tour/ganas.jpg" /></td><td style="color:#FFFFFF; font-family:'Bookman Old Style';font-size:medium;text-align:justify;">Ganesa, literally the lord of ganas is the most universally adored of all Brahmanical deities. The images of Ganesa are found practically in every part of India. The popularity of the god is extended to Nepal, Java, Cambodia, Indonesia and even his worship not unknown in Tibet, Myanmar, China and Japan. The god has been conceived as vighneswara, the lord of obstacles, vighantaka, the remover of calamities, siddhidata, the bestower of success and the divine scribe which gained him the reputation as patron of letters.

The Exhibition consists of twenty images out of one hundred objects of art and crafts representing the icons of Ganesa gifted to the Indian Museum on 5 June, 2000 AD by late Vasant Chowdhury, the celebrated actor and art connoisseur.</td></tr>
    </Table>
</asp:Content>
